- practice-app/website/test/event_test.py
- practice-app/website/test/sport_test.py
- Some tests are updated. 
- Better test is created.
> Tests Updated

- back-end/sports_platform/sports_platform_api/models/models.py
- back-end/sports_platform/sports_platform_api/validation/generic_validators.py
- back-end/sports_platform/sports_platform_api/validation/user_validation.py
> Validators for name, password, birth Date and gender, also db models

- back-end/sports_platform/sports_platform_api/validation/generic_validators.py
- back-end/sports_platform/sports_platform_api/validation/user_validation.py
Validation for Sports, Email, Surname, Skill_level is written.
A generic validator for english characters and "." is written using Regex.
Rules for validations: #147 #150 #153 
Closing #147 #150 #153 
More information: https://kdpisda.medium.com/how-to-validate-the-raw-json-post-request-body-in-django-3c72e4513658
> Validation For Sport Email Surname Skill_level 

- back-end/sports_platform/sports_platform_api/models/__init__.py
- back-end/sports_platform/sports_platform_api/models/sport_models.py
- back-end/sports_platform/sports_platform_api/models/user_models.py
- Since we will have lots of models having separate files will be useful.
> Database files separated

- back-end/sports_platform/sports_platform_api/models/models.py
- back-end/sports_platform/sports_platform_api/models/user_models.py
- back-end/sports_platform/sports_platform_api/validation/user_validation.py
Fixes #164 
I have added it and also added a validation for the date field.
> block relationship model and validator

- back-end/sports_platform/sports_platform_api/models/sport_models.py
- back-end/sports_platform/sports_platform_api/models/user_models.py
I have changed the user model so that we can use the django authorization system properly. Feel free to comment
Closing #185
> User model change and table names

- back-end/.gitignore
- back-end/sports_platform/requirments.txt
- back-end/sports_platform/sports_platform/urls.py
- back-end/sports_platform/sports_platform_api/controllers/__init__.py
- back-end/sports_platform/sports_platform_api/controllers/guest.py
- back-end/sports_platform/sports_platform_api/models/user_models.py
- back-end/sports_platform/sports_platform_api/tests/tests_login.py
- back-end/sports_platform/sports_platform_api/urls.py
- back-end/sports_platform/sports_platform_api/validation/generic_validators.py
- back-end/sports_platform/sports_platform_api/validation/user_validation.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
Closing #173 
Login functionality with tests are implemented.
Users can login using their usernames.
> Login Endpoint

- back-end/sports_platform/sports_platform_api/tests/tests_login.py
Login test is fixed and includes create_mock_user from #209.
> Add create_mock_user To Fix Test

- back-end/sports_platform/sports_platform_api/tests/test_register.py
I fixed the tests. They were failing because we returned "message" in our responses.
closes #215
> fix register tests

- back-end/sports_platform/sports_platform/settings.py
- back-end/sports_platform/sports_platform_api/auth/__init__.py
- back-end/sports_platform/sports_platform_api/auth/error_handler.py
- back-end/sports_platform/sports_platform_api/tests/test_logout.py
- back-end/sports_platform/sports_platform_api/urls.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
Logout endpoint is created.
The token of the user that wants to log out should be provided in the header.
> Create Logout Endpoint

- back-end/sports_platform/sports_platform_api/views/user_views.py
I changed the code, now we do not get any error
Fix #221
> get user bug fix

- back-end/sports_platform/sports_platform_api/tests/test_logout.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
After preparing the automated test workflow, I realized there were two bugs:
1. We changed the response code to 401 for not logged in users
2. Import statement is missing  
These should be fixed
Closing #230
> Fix Test Bugs

- back-end/sports_platform/sports_platform_api/tests/tests_get_user.py
> fix get user test

- back-end/sports_platform/sports_platform_api/models/user_models.py
> gender field is char now

- back-end/sports_platform/sports_platform_api/views/user_views.py
fix response messages based on the integrity error, also make the transaction atomic
Fixes #225
> Fix Issue 225

- back-end/sports_platform/sports_platform_api/tests/test_sport.py
- back-end/sports_platform/sports_platform_api/urls.py
- back-end/sports_platform/sports_platform_api/views/sport_views.py
I have added get sports endpoint to get supported sports. It would be better to merge this PR, after #200 is merged
Closes #219
> get sports api and tests added

- back-end/sports_platform/sports_platform_api/tests/tests_login.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
Since the front-end team requested for the login endpoint to return user_id, I fixed and added it.
> Add User Id to Login

- back-end/sports_platform/manage.py
- back-end/sports_platform/sports_platform_api/controllers/guest.py
- back-end/sports_platform/sports_platform_api/validation/generic_validators.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
Fix #248 
In addition to fixing not allowing 2 names, I fixed the problem related to external sports api that we use. Also, I removed some unnecessary operations in register api
> Backend name bug

- back-end/sports_platform/sports_platform_api/models/user_models.py
- back-end/sports_platform/sports_platform_api/tests/test_set_visibility.py
- back-end/sports_platform/sports_platform_api/tests/test_update_user.py
- back-end/sports_platform/sports_platform_api/urls.py
- back-end/sports_platform/sports_platform_api/validation/user_validation.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
I have implemented set visibility endpoint, also changed the unauthorized response to be consistent.
Fix #178
> add set visibility endpoint, change get user message for unathorization

- back-end/sports_platform/sports_platform_api/tests/test_sport.py
- back-end/sports_platform/sports_platform_api/views/sport_views.py
Fix #233 and #219 
As we have talked I return list of things from now on.
> get sports compatible with scheme

- back-end/sports_platform/sports_platform_api/models/__init__.py
- back-end/sports_platform/sports_platform_api/models/user_models.py
- back-end/sports_platform/sports_platform_api/tests/test_unblock.py
- back-end/sports_platform/sports_platform_api/urls.py
- back-end/sports_platform/sports_platform_api/validation/user_validation.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
> unblock is implemented

- back-end/sports_platform/sports_platform_api/models/user_models.py
- back-end/sports_platform/sports_platform_api/tests/test_delete_user.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
> add delete endpoint

- back-end/sports_platform/sports_platform_api/models/event_models.py
- back-end/sports_platform/sports_platform_api/validation/event_validation.py
Event model and validators are created. SportsEvent schema naming conventions are used which can be found [here](https://schema.org/SportsEvent). These models and validators can be used on event related endpoints.
> Backend event database

- back-end/sports_platform/sports_platform_api/models/user_models.py
- back-end/sports_platform/sports_platform_api/tests/test_get_blocked.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
> get blocked users implemented with tests

- back-end/sports_platform/sports_platform_api/helpers/__init__.py
- back-end/sports_platform/sports_platform_api/helpers/user_filter.py
- back-end/sports_platform/sports_platform_api/tests/tests_get_user.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
Fix #255 
I have changed the function, now visibility of attributes is checked and returned accordingly.
> get user is modified such that invisible fields are not returned

- back-end/sports_platform/sports_platform_api/models/event_models.py
- back-end/sports_platform/sports_platform_api/serializers/event_seralizer.py
- back-end/sports_platform/sports_platform_api/tests/test_get_event.py
- back-end/sports_platform/sports_platform_api/urls.py
- back-end/sports_platform/sports_platform_api/views/event_views.py
> Get Event Endpoint

- back-end/sports_platform/sports_platform_api/models/__init__.py
- back-end/sports_platform/sports_platform_api/models/activity_stream_models.py
- back-end/sports_platform/sports_platform_api/models/event_models.py
- back-end/sports_platform/sports_platform_api/models/user_models.py
Closes #269 
For now, I haven't added activities for participation acceptance and attending as a spectator because I wait for #277 to be merged.
> Backend activity stream DB model and add data into it

- back-end/sports_platform/sports_platform_api/models/event_models.py
- back-end/sports_platform/sports_platform_api/tests/test_participation.py
- back-end/sports_platform/sports_platform_api/views/event_views.py
Skill level was not checked when user requested to join to the event. It is fixed.
Closing #298
> Backend Fix Skill Level Check

- back-end/sports_platform/sports_platform_api/models/user_models.py
- back-end/sports_platform/sports_platform_api/tests/test_user_participation.py
- back-end/sports_platform/sports_platform_api/urls.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
Get requests for events user participating, spectating and interested in.
> Backend User Participation

- back-end/sports_platform/sports_platform_api/models/user_models.py
- back-end/sports_platform/sports_platform_api/tests/test_user_participation.py
As asked on issue #304 , the field wanted by the frontend team is added. sport, date and location.
> Add More Fields To Get User Events

- back-end/sports_platform/sports_platform_api/models/event_models.py
- back-end/sports_platform/sports_platform_api/tests/test_update_event.py
- back-end/sports_platform/sports_platform_api/validation/event_validation.py
- back-end/sports_platform/sports_platform_api/views/event_views.py
> update event endpoint

- back-end/sports_platform/sports_platform_api/models/event_models.py
> bug fix typo is fixed

- back-end/sports_platform/sports_platform_api/tests/test_delete_event.py
- back-end/sports_platform/sports_platform_api/views/event_views.py
> delete event endpoint and tests

- android/AndroidSportsPlatform/.idea/gradle.xml
- android/AndroidSportsPlatform/.idea/misc.xml
- android/AndroidSportsPlatform/app/src/main/AndroidManifest.xml
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/MVVMApplication.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/activities/RegisterActivity.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/UserApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/UserRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/UserRegisterRequest.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/AuthViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/ProfileViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/RegisterViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/RegisterViewModelFactory.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/activity_register.xml
- Splitted view models for login and register.
> - Register functionality added.

- back-end/sports_platform/manage.py
- back-end/sports_platform/sports_platform_api/data/__init__.py
- back-end/sports_platform/sports_platform_api/data/badges.py
- back-end/sports_platform/sports_platform_api/models/__init__.py
- back-end/sports_platform/sports_platform_api/models/badge_models.py
- back-end/sports_platform/sports_platform_api/models/event_models.py
- back-end/sports_platform/sports_platform_api/models/user_models.py
- back-end/sports_platform/sports_platform_api/tests/test_badge.py
- back-end/sports_platform/sports_platform_api/urls.py
- back-end/sports_platform/sports_platform_api/validation/event_validation.py
- back-end/sports_platform/sports_platform_api/validation/user_validation.py
- back-end/sports_platform/sports_platform_api/views/__init__.py
- back-end/sports_platform/sports_platform_api/views/badge_views.py
- back-end/sports_platform/sports_platform_api/views/event_views.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
On this pull request:
- Badges are predefined and can be found under the data folder.
- Badge database is created. There are two types of badges, event and user badges. Event badges are given to event participants after the startDate of the event and decided by the event organizer. User badges can be given between users.
- Get requests for events is written and badges given to the participants is returned.
- Get request for user badges is written and returns both the badges gained by events and other users is returned.
- Post request for both event badges and user badges is created.
> Backend Badge Basics

- front-end/playground/package-lock.json
- front-end/playground/src/pages/NewEvent/NewEvent.css
- front-end/playground/src/pages/NewEvent/NewEvent.js
- front-end/playground/src/pages/SearchPage/EventInfo.css
- front-end/playground/src/pages/SearchPage/EventInfo.js
- front-end/playground/src/pages/SearchPage/SearchPage.css
- front-end/playground/src/pages/SearchPage/SearchPage.js
Page which will be used for searching events has been prepared. Its functionalities had better be working. Also style part is the last version.
> Event search page

- front-end/playground/src/App.js
- front-end/playground/src/pages/Event/EventInformation/EventInformation.js
- front-end/playground/src/pages/Event/ModifyEvent/ModifyEvent.css
- front-end/playground/src/pages/Event/ModifyEvent/ModifyEvent.js
> Modify event basic functionality is implemented

- front-end/playground/src/App.js
- front-end/playground/src/pages/Event/EventInformation/EventInformation.js
- front-end/playground/src/pages/profile/ProfileView.css
- front-end/playground/src/pages/profile/ProfileView.js
- front-end/playground/src/services/User.js
> view profile basic functionality is implemented

- back-end/sports_platform/sports_platform_api/views/event_views.py
> bug fix update event

- android/AndroidSportsPlatform/app/src/main/AndroidManifest.xml
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/activities/LoginActivity.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/activity_login.xml
First activity renamed as LoginActivity instead of MainActivity
> - Renamed the first activity to LoginActivity from MainActivity

- android/AndroidSportsPlatform/app/src/main/AndroidManifest.xml
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/activities/MainActivity.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/adapter/TabBarPagerAdapter.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/HomeFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/TabBarFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/util/Constants.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/AuthViewModel.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/activity_main.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_home.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_tab_bar.xml
- android/AndroidSportsPlatform/app/src/main/res/values/strings.xml
- android/AndroidSportsPlatform/app/src/main/res/values/styles.xml
-The related Fragment, layout and Adapter are created
- MainActivity layout created
- After login, MainActivity is displayed instead of ProfileActivity now
- HomeFragment is created as the first fragment of the app
> - Tabbar integrated to main page

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/MVVMApplication.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/HomeFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/HomeViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/HomeViewModelFactory.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_home.xml
- android/AndroidSportsPlatform/app/src/main/res/values/dimens.xml
- android/AndroidSportsPlatform/app/src/main/res/values/strings.xml
- android/AndroidSportsPlatform/app/src/main/res/values/styles.xml
- Create new event button, logout button and RecycleView for viewing events attending and events created for logged in user
- Text view style is created
- The related ViewModel and ViewModelFactory for homepage are created
> Homepage layout is created

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/MVVMApplication.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/UserApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/UsersParticipatingEvents.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/repository/UserRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/HomeFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/util/Constants.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/AuthViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/AuthViewModelFactory.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/HomeViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/HomeViewModelFactory.kt
- User information is transferred from AuthViewModel to HomeFragment
- Data class for user's participating events is created
> Logged in user's participating(attending) events endpoint is integrated

- back-end/sports_platform/sports_platform_api/serializers/user_serializer.py
- back-end/sports_platform/sports_platform_api/tests/tests_get_user.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
> do not return the user if block operation occurred

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/adapter/UsersParticipatingEventsAdapter.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/HomeFragment.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/item_layout.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/item_users_participating_events_layout.xml
- Adapter created for the RecyclerView which is for user's participating events.
- onCreateViewHolder and onBindViewHolder functions are overridden in adapter
> Item layout for user's participating events is created.

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/adapter/TabBarPagerAdapter.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/SearchFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/SearchViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/SearchViewModelFactory.kt
- android/AndroidSportsPlatform/app/src/main/res/drawable/bg_search.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_search.xml
- android/AndroidSportsPlatform/app/src/main/res/values/dimens.xml
- ViewModel and ViewModelFactory for search are created.
- The layout for the search fragment is created.
- SearchFragment is activated in TabBarPagerAdapter
> SearchFragment is added

- android/AndroidSportsPlatform/.idea/misc.xml
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/UserApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/ResponseMessage.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/UserRegisterResponse.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/repository/UserRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/HomeFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/HomeViewModel.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/activity_search_operations.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_home.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_tab_bar.xml
User logout operation is done. After clicking logout button, user logs out and navigated to the login page.
[Related Issue](https://github.com/bounswe/2021SpringGroup6/issues/374)
> Android - User logout operation is done

- back-end/sports_platform/sports_platform_api/helpers/user_filter.py
- back-end/sports_platform/sports_platform_api/models/user_models.py
- back-end/sports_platform/sports_platform_api/validation/user_validation.py
User model is updated so that the location information is also taken.
This effects the fields of create, update user and set visibility for users.
After the merge API docs will be updated.
Closing #357
> Retrieve Location Information From the User

- back-end/sports_platform/sports_platform_api/models/user_models.py
- back-end/sports_platform/sports_platform_api/serializers/user_serializer.py
- back-end/sports_platform/sports_platform_api/tests/test_search_user.py
- back-end/sports_platform/sports_platform_api/tests/tests_get_user.py
- back-end/sports_platform/sports_platform_api/urls.py
- back-end/sports_platform/sports_platform_api/validation/user_validation.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
> Backend user search

- android/AndroidSportsPlatform/.idea/misc.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_search_user.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/item_searched_user_layout.xml
- android/AndroidSportsPlatform/app/src/main/res/values/strings.xml
Item layout for searched users is created.
Recyclerview for resulting users is done.
> Design for the searched users is done.

- android/AndroidSportsPlatform/app/build.gradle
- android/AndroidSportsPlatform/app/src/debug/res/values/google_maps_api.xml
- android/AndroidSportsPlatform/app/src/main/AndroidManifest.xml
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/MVVMApplication.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/activities/MapsActivity.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/EventApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/requests/CreateEventRequest.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/CreateEventResponse.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/repository/EventRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/CreateEventFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/HomeFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/util/Constants.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/util/String.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/CreateEventViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/CreateEventViewModelFactory.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/activity_maps.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_create_event.xml
- android/AndroidSportsPlatform/app/src/main/res/values/strings.xml
- android/AndroidSportsPlatform/app/src/main/res/values/styles.xml
- android/AndroidSportsPlatform/app/src/release/res/values/google_maps_api.xml
- android/AndroidSportsPlatform/build.gradle
Creating a new event feature is successfully implemented. For choosing location functionality, the Google Cloud maps service is integrated.
> Android create new event

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/MVVMApplication.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/adapter/UserBadgesAdapter.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/adapter/UserSearchAdapter.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/UserApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/requests/AddBadgeRequest.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/requests/UserSearchRequest.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/GetBadgeResponse.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/repository/UserRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/DetailedUserFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodelfactories/DetailedUserViewModelFactory.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/DetailedUserViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/UserSearchViewModel.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_detailed_user.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/item_badge.xml
- android/AndroidSportsPlatform/app/src/main/res/values/strings.xml
Also:
- Badge data models are created.
- Badge adding and getting endpoint are implemented.
- User search operation is done by _identifier_ instead of _name_.
> Android - The layout for Detailed User Page is created.

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/adapter/UsersParticipatingEventsAdapter.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/AdditionalProperty.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/GeoCoordinates.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/Location.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/Value.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/EventResponse.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/UsersParticipatingEvents.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/EventSearchFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/HomeFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/util/String.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/item_users_participating_events.xml
- Create another adapter for user's participating events
- Add another click listener for user's participating events
- Add layout for user's participating events
- Update adapter for user's participating events at home screen
> - Fix user's participating events response models

- back-end/sports_platform/sports_platform_api/models/badge_models.py
- back-end/sports_platform/sports_platform_api/validation/badge_validation.py
- back-end/sports_platform/sports_platform_api/views/badge_views.py
According to requirement 1.4.1.2, users shall be able to request new type of badges from the system.
Therefore, I created an endpoint for users to be able to send new badge requests.
Inputs are:
description, required
sport, optional
closing #344
> New badge request

- back-end/sports_platform/sports_platform_api/views/activity_stream_views.py
> filter activity stream

- back-end/sports_platform/sports_platform_api/models/event_models.py
- back-end/sports_platform/sports_platform_api/tests/test_participation.py
- back-end/sports_platform/sports_platform_api/views/event_views.py
User will be warned when capacity is full but still added to the spectator list compatible with Requirement 1.3.5.3.
Closing #343
> Update Spectating an Event Endpoint to allow more spectators than the capacity

- back-end/sports_platform/sports_platform_api/tests/test_badge.py
- back-end/sports_platform/sports_platform_api/views/event_views.py
This endpoints enable event creators to delete badges to be given to events.
Closing #342
> Delete event badge

- android/AndroidSportsPlatform/app/src/debug/res/values/google_maps_api.xml
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/MVVMApplication.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/activities/MapsActivity.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/adapter/EventsListAdapter.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/SportApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/requests/EventFilterRequest.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/SportsResponse.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/repository/SportRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/EventSearchFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/SearchFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/util/Gson.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodelfactories/SearchViewModelFactory.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/EventSearchViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/SearchViewModel.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_search.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/item_event_layout.xml
- android/AndroidSportsPlatform/app/src/main/res/values/strings.xml
- android/AndroidSportsPlatform/app/src/release/res/values/google_maps_api.xml
The filters (sport type, location etc.) for event search are successfully implemented. Location-based search is also integrated. The user will locate 2 markers into 2 different locations and get the events which take place inside 2 markers(which forms a rectangle).
> Android event search filters implemented

- front-end/playground/package-lock.json
- front-end/playground/src/App.js
- front-end/playground/src/pages/EquipmentInformation/EquipmentInformation.css
- front-end/playground/src/pages/EquipmentInformation/EquipmentInformation.js
- front-end/playground/src/pages/EquipmentInformation/EquipmentInformationFunctional.js
- front-end/playground/src/pages/NewEquipment/NewEquipment.css
- front-end/playground/src/pages/NewEquipment/NewEquipment.js
- front-end/playground/src/pages/NewEvent/NewEvent.js
- front-end/playground/src/pages/NewField/NewField.css
- front-end/playground/src/pages/NewField/NewField.js
- front-end/playground/src/pages/SearchEquipment/EquipmentInfo.css
- front-end/playground/src/pages/SearchEquipment/SearchEquipment.css
- front-end/playground/src/pages/SearchEquipment/SearchEquipment.js
- front-end/playground/src/pages/SearchField/SearchField.css
- front-end/playground/src/pages/SearchField/SearchField.js
- front-end/playground/yarn.lock
The main skeleton for pages related with equipment has been prepared. Also badge feature has been added to opening a new event.
> Open new equipment page

- back-end/sports_platform/sports_platform_api/helpers/user_filter.py
- back-end/sports_platform/sports_platform_api/models/user_models.py
- back-end/sports_platform/sports_platform_api/validation/user_validation.py
- back-end/sports_platform/sports_platform_api/views/user_views.py
Closes #356 
For the "create events" option, I just return a boolean so client side can use it to decide if they should be shown
> add visibility options

- back-end/sports_platform/manage.py
- back-end/sports_platform/sports_platform_api/data/badges.py
- back-end/sports_platform/sports_platform_api/models/badge_models.py
- back-end/sports_platform/sports_platform_api/models/event_models.py
- back-end/sports_platform/sports_platform_api/models/user_models.py
- back-end/sports_platform/sports_platform_api/tests/test_badge.py
- back-end/sports_platform/sports_platform_api/urls.py
- back-end/sports_platform/sports_platform_api/views/badge_views.py
We made it possible to add badges specific to sports.
> Sport Specific Badges

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/MVVMApplication.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/adapter/UserListAdapter.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/UserApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/requests/UserDetailRequest.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/requests/UserSearchRequest.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/repository/UserRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/SearchFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/UserDetailFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/UserSearchFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodelfactories/UserDetailViewModelFactory.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/AuthViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/ProfileFragmentViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/SearchViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/UserDetailViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/UserSearchViewModel.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_detailed_user.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/item_searched_user_layout.xml
Now, Users are able to search all other users with typing their identifier.
Other fields of searching a User will be added soon.
Related issues: [issue1](https://github.com/bounswe/2021SpringGroup6/issues/402), [issue2](https://github.com/bounswe/2021SpringGroup6/issues/372)
> Android user search implementation is done.

- front-end/playground/src/PermanentComponents/Header.js
Menu options changes have been made in the header.
> Some styling changes like adding different links has been made.

- front-end/playground/src/pages/EquipmentInformation/EquipmentInformation.js
- front-end/playground/src/pages/NewEquipment/NewEquipment.js
- front-end/playground/src/pages/SearchEquipment/EquipmentInfo.css
- front-end/playground/src/pages/SearchEquipment/EquipmentInfo.js
- front-end/playground/src/pages/SearchEquipment/SearchEquipment.js
- front-end/playground/src/pages/SearchPage/SearchPage.js
The implemented pages include open a new one, search and view.
> Pages related with equipments has been prepared

- front-end/playground/src/pages/EquipmentInformation/EquipmentInformation.js
- front-end/playground/src/pages/NewEquipment/NewEquipment.js
They were mainly related with the case where you don't give an image for the equipment.
> Bugs related with open a new equipment and view equipment were fixed.

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/MVVMApplication.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/adapter/InterestedsOfEventAdapter.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/EventApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/User.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/requests/DecideParticipantsRequest.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/requests/EventFilterRequest.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/DecideParticipantsResponse.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/GetInterestedsOfEventResponse.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/repository/EventRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/EventDetailFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/HomeFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/ShowInterestedsDialogFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/util/DialogDismissListener.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodelfactories/HomeViewModelFactory.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodelfactories/ShowInterestedsViewModelFactory.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/EventDetailViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/HomeViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/ShowInterestedsViewModel.kt
- android/AndroidSportsPlatform/app/src/main/res/drawable/ic_check_circle.xml
- android/AndroidSportsPlatform/app/src/main/res/drawable/ic_decline_circle.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_event_detail.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_home.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_show_interesteds.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/item_interesteds_of_event_layout.xml
- android/AndroidSportsPlatform/app/src/main/res/values/strings.xml
The user's created events are now viewed on Home Page. The creator is able to accept or reject the interested users on his/her created events' Detail Page.
> Android users created events

- front-end/playground/src/pages/NewEvent/NewEvent.js
Badges for soccer and basketball have been changed and specialized.
> Sport specific badge options have been changed.

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/MVVMApplication.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/adapter/EventBadgesAdapter.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/BadgeApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/EventApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/requests/AddBadgeToEventRequest.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/BadgesResponse.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/CreateEventResponse.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/GetEventBadgesResponse.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/repository/BadgeRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/repository/EventRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/AddEventBadgeFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/CreateEventFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/EventDetailFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/util/String.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodelfactories/AddEventBadgeViewModelFactory.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/AddEventBadgeViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/CreateEventViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/CreateEventViewModelFactory.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/EventDetailViewModel.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_add_event_badge.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_create_event.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_event_detail.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/item_event_badges_layout.xml
- android/AndroidSportsPlatform/app/src/main/res/values/strings.xml
The event badge implementation is finished. The user is now able to add badges to events. Moreover, the user is able to add sport specific badges to events. The badges of the events are shown on their Event Detail Page.
> Android event badges

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/UserDetailFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/UserDetailViewModel.kt
Badge implementation to a User is completed.
User can add a badge to another user.
[Related issue](https://github.com/bounswe/2021SpringGroup6/issues/403)
There is a bug that user logs out after adding a badge, later will be fixed soon.
> Android badge implementation completed.

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/UserApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/requests/UserUpdateRequest.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/repository/UserRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/ProfileFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/ProfileFragmentViewModel.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_profile.xml
User now able to update his/her own profile by typing a different _email_, _name_, _family name_, _gender_ or _birth date_.
[Related issue](https://github.com/bounswe/2021SpringGroup6/issues/364)
> Android - User Updating Profile feature is implemented

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/EventApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/repository/EventRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/EventDetailFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/util/Popup.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/CreateEventViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/EventDetailViewModel.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_event_detail.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/item_popup_layout.xml
- android/AndroidSportsPlatform/app/src/main/res/values/strings.xml
Event deletion feature is added. User can delete an event only if it was created by that user. The delete button is in the Event Detail Page.
> Android delete event

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/EventApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/SportApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/UserApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/util/ErrorInterceptor.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/AuthViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/CreateEventViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/EventDetailViewModel.kt
Added error interceptor to okhttp client to show user a more obvious error message. Implemented that error interceptor on some screens.
> Android - Error handling in API call responses

- back-end/sports_platform/sports_platform_api/data/badges.py
- back-end/sports_platform/sports_platform_api/models/event_models.py
- back-end/sports_platform/sports_platform_api/models/user_models.py
For the requirement:
1.4.2.2 Users shall be able to acquire badges as event creators.
Event creator users will acquire "event creator" badge.
> Event creator badges

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/adapter/UserFollowingAdapter.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/UserApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/Actor.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/AdditionalPropertyBadge.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/AdditionalPropertyBadgeGivenBy.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/Badge.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/Items.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/Object.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/ValueBadge.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/requests/UserFollowingRequest.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/GetBadgeResponse.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/responses/GetFollowingUsersResponse.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/repository/UserRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/UserDetailFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/UserDetailViewModel.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_detailed_user.xml
- android/AndroidSportsPlatform/app/src/main/res/layout/item_following_users.xml
- Now user may search a user and add badge to the user. Then he/she can see the badges as a list.
- And also, following user operation is done. Users are able to follow each other. Moreover they can see the followers identifiers of each other.
[Related issues of adding badges ](https://github.com/bounswe/2021SpringGroup6/issues/403)
[Related issues of displaying badges ](https://github.com/bounswe/2021SpringGroup6/issues/446)
[Related issue of following users ](https://github.com/bounswe/2021SpringGroup6/issues/316)
> Badge list of navigated User is correctly designed and implemented

- front-end/playground/src/pages/Notifications/index.js
- front-end/playground/src/pages/Notifications/style.css
Notification page setted, let's move this code to our baseline
> notification page implemented

- front-end/playground/src/pages/NewEquipment/NewEquipment.js
- front-end/playground/src/pages/NewEvent/NewEvent.js
- front-end/playground/src/pages/SearchEquipment/SearchEquipment.js
- front-end/playground/src/pages/SearchPage/SearchPage.js
Now any user can use it for both events and equipments in the context of opening a new one and searching.
> Ultimate Frisbee game has been added to the system.

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/activities/MapsActivity.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/GeoCoordinates.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/CreateEventFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/EventDetailFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/SearchFragment.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_event_detail.xml
- android/AndroidSportsPlatform/app/src/main/res/values/strings.xml
Showing the location of the event on Event Detail Page feature is successfully implemented. When user clicks the button, he/she is directed to the map, which shows the location of the event as blue marker.
> Android add map to event detail page

- android/AndroidSportsPlatform/app/release/output.json
- android/AndroidSportsPlatform/app/src/main/res/values/strings.xml
> hotfix on strings.xml

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/UserApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/models/requests/UserUnFollowingRequest.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/repository/UserRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/UserDetailFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/UserDetailViewModel.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_detailed_user.xml
- android/AndroidSportsPlatform/app/src/main/res/values/strings.xml
Users now able to unfollow another profiles with pressing a button which is in the detail page of Users
[Related issue](https://github.com/bounswe/2021SpringGroup6/issues/363)
[Related commit](https://github.com/bounswe/2021SpringGroup6/commit/e167a8033ab5c21e726fe5b08a7fa91fd3c4537a)
> Android - User Unfollowing operation is implemented

- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/api/UserApi.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/data/repository/UserRepository.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/fragments/ProfileFragment.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/ProfileFragmentViewModel.kt
- android/AndroidSportsPlatform/app/src/main/java/com/example/sportsplatform/viewmodels/RegisterViewModel.kt
- android/AndroidSportsPlatform/app/src/main/res/layout/fragment_profile.xml
- android/AndroidSportsPlatform/app/src/main/res/values/strings.xml
- Users now able to delete their profiles. After that, they need to register again.
- Also register user bug is fixed. Now after registering User goes to login page and needs to log in.
[Related issue](https://github.com/bounswe/2021SpringGroup6/issues/360)
[Related commit](https://github.com/bounswe/2021SpringGroup6/commit/a0d2144ae625ba676a9d4f20146db6cd919776fc)
> Android - User Profile Deleting operation is implemented
